// This follows a different format to the other gamedata files.
// It simply assigns variable names to network table property name strings.
// Network names are classname/propname, e.g. CBasePlayer/m_fWhatever

off_entpos CBaseEntity/m_vecOrigin
// look angles, currently just for L4D1/2, can add other games as needed
off_eyeang "CCSPlayer/m_angEyeAngles[0]"

// vi: sw=4 ts=4 noet tw=80 cc=80 ft=plain
