// = inputsystem library =

vtidx_SleepUntilInput {
	default 31 // TODO(compat): don't really know yet if this causes any issues
	Portal2 34 // IAppSystem changes
}

// XXX: This function won't always exist even when has_ is true.
// It's only used by rinput.c after checking that m_rawinput exists.
vtidx_GetRawMouseAccumulators {
	L4D2 37
	2013 39
	Portal2 50
}

// vi: sw=4 ts=4 noet tw=80 cc=80 ft=plain
