/*
 * Copyright © Michael Smith <mikesmiffy128@gmail.com>
 * Copyright © Willian Henrique <wsimanbrazil@yahoo.com.br>
 * Copyright © Hayden K <imaciidz@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

#include <stdlib.h> // used in generated code
#include <string.h> // "

#include "abi.h" // for NVDTOR use in gamedata generated code
#include "con_.h"
#include "engineapi.h"
#include "gamedata.h"
#include "gameinfo.h"
#include "gametype.h"
#include "intdefs.h"
#include "langext.h"
#include "mem.h" // "
#include "os.h"
#include "vcall.h"
#include "x86.h"

u32 _gametype_tag = 0; // declared in gametype.h but seems sensible enough here

ifacefactory factory_client = 0, factory_server = 0, factory_engine = 0,
		factory_inputsystem = 0;

struct VEngineClient *engclient;
struct VEngineServer *engserver;

struct IServerGameDLL *srvdll;

DECL_VFUNC(void, struct CGlobalVars *, GetGlobalVars, 1) // seems very stable
struct CGlobalVars *globalvars;

struct IInputSystem *inputsystem;
struct CEngineVGui *vgui;
struct CServerPlugin *pluginhandler;

DECL_VFUNC_DYN(struct IServerGameDLL, struct ServerClass *, GetAllServerClasses)

#include <entpropsinit.gen.h> // generated by build/mkentprops.c
#include <gamedatainit.gen.h> // generated by build/mkgamedata.c

bool engineapi_init(int pluginver) {
	if_cold (!con_detect(pluginver)) return false;
	pluginhandler = factory_engine("ISERVERPLUGINHELPERS001", 0);

	if (engclient = factory_engine("VEngineClient015", 0)) {
		_gametype_tag |= _gametype_tag_Client015;
	}
	else if (engclient = factory_engine("VEngineClient014", 0)) {
		_gametype_tag |= _gametype_tag_Client014;
	}
	else if (engclient = factory_engine("VEngineClient013", 0)) {
		_gametype_tag |= _gametype_tag_Client013;
	}
	else if (engclient = factory_engine("VEngineClient012", 0)) {
		_gametype_tag |= _gametype_tag_Client012;
	}

	if (engserver = factory_engine("VEngineServer021", 0)) {
		_gametype_tag |= _gametype_tag_Server021;
	}
	else if (engserver = factory_engine("VEngineServer022", 0)) {
		//_gametype_tag |= _gametype_tag_Server022; // not needed yet
	}
	// else if (engserver = others as needed...) {
	// }

	void *pim = factory_server("PlayerInfoManager002", 0);
	if (pim) globalvars = GetGlobalVars(pim);

	vgui = factory_engine("VEngineVGui001", 0);

	// TODO(compat): add this back when there's gamedata for 009 (no point atm)
	/*if (srvdll = factory_server("ServerGameDLL009", 0)) {
		_gametype_tag |= _gametype_tag_SrvDLL009;
	}*/
	if (srvdll = factory_server("ServerGameDLL005", 0)) {
		_gametype_tag |= _gametype_tag_SrvDLL005;
	}

	// detect p1 for the benefit of specific features
	if (!GAMETYPE_MATCHES(Portal2)) {
		if (con_findcmd("upgrade_portalgun")) {
			_gametype_tag |= _gametype_tag_Portal1;
			if (!con_findvar("tf_escort_score_rate")) {
				_gametype_tag |= _gametype_tag_Portal1_3420;
			}
		}
		else if (con_findcmd("phys_swap")) {
			_gametype_tag |= _gametype_tag_HL2series;
		}
	}

	if (GAMETYPE_MATCHES(L4D1)) {
		// Crash Course update
		if (con_findcmd("director_log_scavenge_items")) {
			_gametype_tag |= _gametype_tag_L4D1_1015plus;
		}
		// seems there was some code shuffling in the Mac update (1022)
		// this update came like 2-3 weeks after The Sacrifice itself released
		if (con_findvar("tank_stasis_time_suicide")) {
			_gametype_tag |= _gametype_tag_L4D1_1022plus;
		}
	}

	if (GAMETYPE_MATCHES(L4D2)) {
		if (con_findvar("sv_zombie_touch_trigger_delay")) {
			_gametype_tag |= _gametype_tag_L4D2_2125plus;
		}
		if (con_findvar("director_cs_weapon_spawn_chance")) {
			_gametype_tag |= _gametype_tag_TheLastStand;
		}
	}
	initgamedata();
	con_init();
	if_cold (!gameinfo_init()) { con_disconnect(); return false; }
	return true;
}

void engineapi_lateinit() {
	// from AM L4D2 SDK headers:
	// > SENDPROP_VECTORELEM makes [the offset] negative to start with so we
	// > can detect that and set the SPROP_IS_VECTOR_ELEM flag.
	// by doing this at the deferred stage, we avoid having to abs() everything
	if (srvdll && has_vtidx_GetAllServerClasses && has_sz_SendProp &&
			has_off_SP_varname && has_off_SP_type && has_off_SP_offset &&
			has_DPT_DataTable) {
		initentprops(GetAllServerClasses(srvdll));
	}
}

// vi: sw=4 ts=4 noet tw=80 cc=80
