/*
 * Copyright © Michael Smith <mikesmiffy128@gmail.com>
 *
 * Permission to use, copy, modify, and/or distribute this software for any
 * purpose with or without fee is hereby granted, provided that the above
 * copyright notice and this permission notice appear in all copies.
 *
 * THE SOFTWARE IS PROVIDED “AS IS” AND THE AUTHOR DISCLAIMS ALL WARRANTIES WITH
 * REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED WARRANTIES OF MERCHANTABILITY
 * AND FITNESS. IN NO EVENT SHALL THE AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT,
 * INDIRECT, OR CONSEQUENTIAL DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM
 * LOSS OF USE, DATA OR PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR
 * OTHER TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
 * PERFORMANCE OF THIS SOFTWARE.
 */

#ifndef INC_GAMEDATA_H
#define INC_GAMEDATA_H

#include "gametype.h"

// this defaults to zero (tentative definition), but gets defined to a value by
// GAMESPECIFIC() in feature.h. static const int variables get constant-folded
// even in -O0. so, this lets us short-circuit has_ checks inside features.
// we also check if a gamedata entry's
__attribute((unused))
static const int _gamedata_feattags;

// STUPID HACK to avoid pollution if abi.h not already included (only because
// generated gamedata stuff relies on this being defined)
#ifndef NVDTOR
#ifdef _WIN32
#define NVDTOR 1
#else
#define NVDTOR 2
#endif
#endif
#include <gamedata.gen.h> // generated by build/mkgamedata.c
#include <entprops.gen.h> // generated by build/mkentprops.c
#ifndef INC_ABI_H // YUCK YUCK YUCK
#undef NVDTOR
#endif

#endif

// vi: sw=4 ts=4 noet tw=80 cc=80
